project:
  type: website
  render:
   - index.qmd
   - about.qmd
   - projects.qmd
   - resume.qmd


website:
  title: "csu-portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects


format:
  html:
    theme:
      - default
      - styles.scss
    toc: true
    css: styles.css
    page:
      favicon: favicons.png

resources:
  - favicon.png

editor: visual

