project:
  type: website
  output-dir: docs
  render:
   - index.qmd
   - about.qmd
   - projects.qmd
   - resume.qmd
format:
  html:
    self-contained: true
    theme:
      - default
      - styles.scss
    toc: true
    css: styles.css

website:
  title: "csu-portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects


editor: visual

